### ISSUE TITLE
Simulation Gazebo without Joystick

### ISSUE THREAD

**Issue by GabrielKoenig** [tudelft/paparazzi#43]
It would be nice if the simulation could run without any joystick. 
-> at the moment the start up of the simulation gets stuck if there is no telemetry (problem occured especciall in the branch mavlabCourse2018)
I would propose
- if GCS detects joystick, joystick inputs can be used
- if GCS doesn detect joystick, commands over the console are valid (or probably simple command actions as takeoff, ATT,NAV,...

Especially for fully autonomous flight and for developping purpose, joystick is not needed.

**Comment by tomvand** [comment]
The simulation is already working without a joystick, but only in NAV mode (since you can't provide control inputs). You can use the flight plan in the GCS to start the drone just as you described. Check out the autonomous flight->simulation section in [Part 2](https://tudelft.github.io/coursePaparazzi/) of the course documentation.

You can stop the joystick command in the session to hide the error messages, and you can save your session under a different name if you do not want to start the joystick every time.

**Comment by GabrielKoenig** [comment]
okey thats nice to hear. I made the wrong conclusion, when my GCS gave me the message  "Waiting for telemetry". 

But may I ask, what could be the issue for my error message?
Gazebo is starting with the proper world and I added the in the bashrc the line export "GAZEBO_MODEL_PATH=/home/gabriel/Programme/paparazzi/conf/simulator/gazebo/models:$GAZEBO_MODEL_PATH"
But CGS keeps to be an empty window only with the error messag displayed

**Comment by GabrielKoenig** [comment]
I mean with "export GAZEBO_MODEL_PATH=...."

**Comment by tomvand** [comment]
Can you please check the following:
1) Does the gazebo client open (the 3d view)?
2) In the bottom line of the client, does the Sim time run in real time?
3) What is your fps? (bottom right)
4) What version of Gazebo are you running? (Help -> About)

**Comment by GabrielKoenig** [comment]
1. Yes it opens the 3D vew. (see picture)
2. The simulation doesn't run
3. empty
![screenshot from 2018-02-28 11-43-20](https://user-images.githubusercontent.com/22919543/36783549-b2770788-1c7c-11e8-8180-d5714f5b7a07.png)
![screenshot from 2018-02-28 11-29-59](https://user-images.githubusercontent.com/22919543/36783550-b28d40ca-1c7c-11e8-9988-ea2d949d5d60.png)


4. I use gazebo version 7.0.0

**Comment by GabrielKoenig** [comment]
I also tried to remove the joystic and redo the simulator.

**Comment by tomvand** [comment]
Please pull the latest version of the mavlabCourse2018 branch, I think this should fix your problem. Can you let me know if it worked?

**Comment by GabrielKoenig** [comment]
Thanks a lot. Yes, now everything works I can fly the path properly. Is the bepobs horizontal field of view exactly 3.67 or was this just an estimate? Is it a big difference if we limit this size to 3.0 respectively do you propose to switch to gazebo 8? I would prefer to stick with 7 for the moment if possible....

Just one thing I realized, is it normal that camera streaming (through VLC) buffers a lot (up to 6sec where the image is frozen...)

**Comment by tomvand** [comment]
Glad to hear it's working now!
The 3.67 is the maximum field-of-view of the camera, but in practice only a small region around the center of this image is used (at least in the example) so I do not think this will impact you too much.
I recommend you to stick with Gazebo 7, as 8 is not available through ubuntu's package manager and seems to have performance issues on some pc's.

The buffering video is a known bug. The issue lies somewhere in the streaming though, within paparazzi itself the video rate is stable.



-------- Oorspronkelijk bericht --------
Van Gabriel <notifications@github.com>
Datum: 28-02-2018 18:00 (GMT+01:00)
Aan tudelft/paparazzi <paparazzi@noreply.github.com>
CC Tom van Dijk <tomvand@hotmail.com>,Comment <comment@noreply.github.com>
Onderwerp Re: [tudelft/paparazzi] Simulation Gazebo without Joystick (#43)



Thanks a lot. Yes, now everything works I can fly the path properly. Is the bepobs horizontal field of view exactly 3.67 or was this just an estimate? Is it a big difference if we limit this size to 3.0 respectively do you propose to switch to gazebo 8? I would prefer to stick with 7 for the moment if possible....

Just one thing I realized, is it normal that camera streaming (through VLC) buffers a lot (up to 6sec where the image is frozen...)

**Comment by GabrielKoenig** [comment]
Thanks for the clarification.
